apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: entry-route
  namespace: default
spec:
  gateways:
  - knative-shared-gateway.knative-serving.svc.cluster.local
  hosts:
  - example.com
  http:
  - match:
    - uri:
        prefix: "/customer"
    rewrite:
      authority: customer.default.example.com
      uri: "/"
    route:
      - destination:
          host: knative-ingressgateway.istio-system.svc.cluster.local
        weight: 100
  - match:
    - uri:
        prefix: "/transaction"
    rewrite:
      authority: transaction.default.example.com
      uri: "/"
    route:
      - destination:
          host: knative-ingressgateway.istio-system.svc.cluster.local
        weight: 100