apiVersion: serving.knative.dev/v1alpha1 
kind: Configuration
metadata:
  name: customer
  namespace: default 
spec:
  revisionTemplate:
    metadata:
      labels:
        knative.dev/type: container
    spec:
      container:
        image: mirfanmcs/customer:v2
        env:
        - name: PORT 
          value: "8080"
        readinessProbe:
          httpGet:
            path: /health
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 15

